language: cpp
compiler:
    - gcc
    - clang
env:
    - CFGFLAGS= CXXFLAGS= LDFLAGS=
matrix:
    include:
        - compiler: clang
          env: CFGFLAGS=--enable-debug CXXFLAGS="-fsanitize=address -O1 -fno-omit-frame-pointer -fno-optimize-sibling-calls" LDFLAGS=-fsanitize=address
        - compiler: clang
          env: CFGFLAGS=--enable-debug CXXFLAGS="-fsanitize=thread -O1" LDFLAGS=-fsanitize=thread
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libperl-dev python3-dev tcl-dev libsasl2-dev libgtest-dev libicu-dev
    - apt-cache show swig
    - ( cd ~ && wget http://prdownloads.sourceforge.net/swig/swig-2.0.8.tar.gz && tar xvf swig-2.0.8.tar.gz && cd swig-2.0.8 && ./configure && make && sudo make install )
script:
    - ./bootstrap.sh
    - mkdir build
    - cd build
    - ../configure --enable-perl --enable-python --enable-tcl --enable-cyrus --with-gtest=/usr/src/gtest $CFGFLAGS
    - cat config.log
    - make V=1
    - make V=1 test
    - sudo make install
notifications:
    irc:
        channels:
            - "irc.freenode.net#znc"
            - "irc.paraphysics.net#znc"
        on_success: always
        on_failure: always
