language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq swig libperl-dev python3-dev tcl-dev libsasl2-dev
script:
    - ./bootstrap.sh
    - mkdir build
    - cd build
    - ../configure --enable-perl --enable-python --enable-tcl --enable-cyrus
    - make
    - sudo make install
notifications:
    irc:
        channels:
            - "irc.freenode.net#znc"
            - "irc.shoutcast.com#znc"
        on_success: always
        on_failure: always
